### ISSUE TITLE
Clarify shared hosting providers non-support

### ISSUE THREAD

**Issue by jtojnar** [simplepie/simplepie-ng#32]
Quoting the readme:

> Will almost certainly not work with shared hosting providers. Time to get a grown-up server.

Since this is supposed to be just a PHP library, why would that not work on shared hosting providers?

The support for shared hosting providers is still important because, for example, for students, especially in less wealthy countries, shared hosting might be the only way to afford a “private cloud”. I was also relying on that until very recently. And even if one has the money, running a server takes significantly more effort.

Also, the ability to deploy applications to a shared hosting is the only reason why I still use PHP at all – on my own server I can just use the better languages.

**Comment by skyzyx** [comment]
> Since this is supposed to be just a PHP library, why would that not work on shared hosting providers?

Because most shared hosting providers leverage _trailing edge_ technology.  Most of these providers have not even made the jump to PHP 7.0 yet, while the 7.2 branch was cut last night. Also, having spent many years working on SimplePie and providing support for its users, I learned that many providers do not have the proper `libxml2` or internationalization extensions installed.

My focus for this project is to target _professional-grade_ developers. If your shared hosting provider has support for all of the dependencies, that’s cool. But in terms of support, shared hosting providers is not a goal for me. 

> The support for shared hosting providers is still important because, for example, for students, especially in less wealthy countries, shared hosting might be the only way to afford a “private cloud”.

You are certainly correct here.

> I was also relying on that until very recently. And even if one has the money, running a server takes significantly more effort.

Perhaps. But again, I’m targeting _professional-grade_ developers.

With offerings from Google Cloud,  Microsoft Azure, and Amazon ECS, it’s pretty trivial to deploy a Docker container running your application. I am planning to provide both a `Vagrantfile` for local development, as well as a `Dockerfile` and base image for Docker deployments.

This is pretty standard stuff for _professional-grade_ developers at this point in software engineering history.

> Also, the ability to deploy applications to a shared hosting is the only reason why I still use PHP at all – on my own server I can just use the better languages.

Well, that’s pretty subjective, but sure. Feed Parser is an excellent project for the Python community, and I have one bookmarked for Ruby that I can share with you once I get back to my computer. Java has Rome, but that’s a bit more complex to get working in the way that you expect.

I apologize if this is disappointing, but I’m only one person. If I look at this from the perspective of a project manager, the first thing I need to focus on is getting a 1.0 built and out the door. Given infinite time and resources, I would support every good idea I could find. But I have _limited_ time and resources, so I need to prioritize. Some things are above the line, while others are below. At present, support for shared hosting providers is below the line.
